// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6X6TVxTsZ_4MrVb9eMvXGVv9t8GOWZzs',
    appId: '1:263858244115:web:5da7d0e6844300b6908de6',
    messagingSenderId: '263858244115',
    projectId: 'storagemanagerapp-1fa0d',
    authDomain: 'storagemanagerapp-1fa0d.firebaseapp.com',
    storageBucket: 'storagemanagerapp-1fa0d.appspot.com',
    measurementId: 'G-KT0LQYXC2W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAthR9vLLzhelOWy9FHZc50t56DVq132c0',
    appId: '1:263858244115:android:3aba3e5fc50773e6908de6',
    messagingSenderId: '263858244115',
    projectId: 'storagemanagerapp-1fa0d',
    storageBucket: 'storagemanagerapp-1fa0d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWC7Afl1P5hok3BEuow6bHsxan2NcTr_Y',
    appId: '1:263858244115:ios:0a99adb9247f2c52908de6',
    messagingSenderId: '263858244115',
    projectId: 'storagemanagerapp-1fa0d',
    storageBucket: 'storagemanagerapp-1fa0d.appspot.com',
    iosClientId: '263858244115-muv6t61b09rbgq3ntafmqecac17b68fu.apps.googleusercontent.com',
    iosBundleId: 'com.stefandojcinovic.storageManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWC7Afl1P5hok3BEuow6bHsxan2NcTr_Y',
    appId: '1:263858244115:ios:703bd5a0c2c0d6c0908de6',
    messagingSenderId: '263858244115',
    projectId: 'storagemanagerapp-1fa0d',
    storageBucket: 'storagemanagerapp-1fa0d.appspot.com',
    iosClientId: '263858244115-ihhqlv9r4c1baovpubo4919l8jg8j8ok.apps.googleusercontent.com',
    iosBundleId: 'com.example.storageManagementApp',
  );
}
